### ISSUE TITLE
测速端更换

### ISSUE THREAD

**Issue by RenaLio** [arielherself/blusterSpeed#1]
是否使用开源misospeed完成测速和流媒体检测，miaospeed地址：https://github.com/miaokobot/miaospeed

**Comment by arielherself** [comment]
我看了一下您发的仓库，MiaoSpeed默认使用cachefly的200mb文件作为下载测试。然而这样做对于blusterSpeed会有两个问题：

- 您可以看一下[cachefly拥有的所有IP](https://ipinfo.io/AS30081)，其全部位于美国。考虑到我们经常使用的网站有很多都配置了全球CDN，我认为这样测试并不准确；
- 该方法只能用于下载检测，而我还想实现上传检测，因为有时候上传速度可能会成为下载速度的瓶颈（尤其在带宽较小的情况下）。

对于流媒体解锁检测，我已经以比较简洁的方式实现了，参考了一个[VPS解锁检测仓库](https://github.com/lmc999/RegionRestrictionCheck)。
